[build-system]
requires = ["setuptools", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "CAP"
version = "0.0.1"
requires-python = ">=3.8"
license = {"file" = "LICENSE"}

[tool.setuptools]
packages = ["CAP"]